# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fireauth < Formula
  desc "CLI tool for authenticating against Firebase and managing bearer tokens for REST API testing."
  homepage "https://github.com/andrespd99/fireauth"
  version "1.0.0-beta.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andrespd99/fireauth/releases/download/v1.0.0-beta.2/fireauth_darwin_amd64.tar.gz"
      sha256 "f21f8c88228072919fa8f7e4111de30ad9765d51b31d09f4c55643e9998e453d"

      define_method(:install) do
        bin.install "fireauth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andrespd99/fireauth/releases/download/v1.0.0-beta.2/fireauth_darwin_arm64.tar.gz"
      sha256 "03908fd217afa22b40a37a2070b17a04e00da6455d477d66628d8a9047f90e76"

      define_method(:install) do
        bin.install "fireauth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrespd99/fireauth/releases/download/v1.0.0-beta.2/fireauth_linux_amd64.tar.gz"
      sha256 "be3c2ba29f3ae919780f164c89d1369cde91c2c1957d4b67e9c36351084f6dc8"
      define_method(:install) do
        bin.install "fireauth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrespd99/fireauth/releases/download/v1.0.0-beta.2/fireauth_linux_arm64.tar.gz"
      sha256 "f1058ca79b9a08de1c2408555fc0a6a5e38ff59acb95e7faa88635461bfd92f5"
      define_method(:install) do
        bin.install "fireauth"
      end
    end
  end

  test do
    system "#{bin}/fireauth", "--help"
  end
end
