# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fireauth < Formula
  desc "CLI tool for authenticating against Firebase and managing bearer tokens for REST API testing."
  homepage "https://github.com/andrespd99/fireauth"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andrespd99/fireauth/releases/download/v1.0.0/fireauth_darwin_amd64.tar.gz"
      sha256 "f250b9509b9da12811aa10e7e6bc0913a7db3c9230d02c19dbbb6338cadeeb14"

      define_method(:install) do
        bin.install "fireauth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andrespd99/fireauth/releases/download/v1.0.0/fireauth_darwin_arm64.tar.gz"
      sha256 "52452cdd1e38887e13f906a3df0938cb51c18fee12938e22eca6d6afcf149851"

      define_method(:install) do
        bin.install "fireauth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrespd99/fireauth/releases/download/v1.0.0/fireauth_linux_amd64.tar.gz"
      sha256 "0e701573b899c7ab567489a4b998e0c200c581e6816217ea1d16d3a52d53eb4d"
      define_method(:install) do
        bin.install "fireauth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andrespd99/fireauth/releases/download/v1.0.0/fireauth_linux_arm64.tar.gz"
      sha256 "a8c78d078e72f83a87bfc49734db635ac6d0b0c23d50983bc98321c7a8aa8e55"
      define_method(:install) do
        bin.install "fireauth"
      end
    end
  end

  test do
    system "#{bin}/fireauth", "--help"
  end
end
